name: PROD - Deploy to Deployment Server

on:
  push:
    branches:
      - master  # Run when code is merged or pushed to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ› ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ”‘ Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.DEPLOY_SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy code to production server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_SERVER_HOST }} "cd public_html/MrPlentl.com && git pull origin master"

